
name: Generate standalone exe for linux

on: [push]

jobs:
  build:
    name: build python packages
    runs-on: ubuntu-latest
    container: centos:8
    steps:
      - name: install tools and python 3.8
        run: yum install -y python38-setuptools.noarch python38-wheel-wheel.noarch python38-setuptools-wheel.noarch python38-pip.noarch python3-virtualenv.noarch git
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: create venv
        run: virtualenv-3 -p python3.8 venv
      - name: install deps
        run: venv/bin/pip install --upgrade -e .
      - name: install pyinstaller
        run: venv/bin/pip install git+https://github.com/pyinstaller/pyinstaller
      - name: generate exe
        run: venv/bin/pyinstaller --onefile --windowed ./amda_sciqlop_speed_tester/speed_tester.spec
      - uses: actions/upload-artifact@v2
        with:
          name: speed_tester-linux
          path: dist/speed_tester

